-- CreateTable
CREATE TABLE "KwhPrice" (
    "id" SERIAL NOT NULL,
    "avg" DOUBLE PRECISION NOT NULL,
    "kwh" DOUBLE PRECISION NOT NULL,
    "biaya" DOUBLE PRECISION NOT NULL,
    "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "KwhPrice_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Hasil" (
    "id" SERIAL NOT NULL,
    "nobooster" DOUBLE PRECISION NOT NULL,
    "booster" DOUBLE PRECISION NOT NULL,
    "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Hasil_pkey" PRIMARY KEY ("id")
);
